# Generated by Django 4.0.6 on 2022-07-29 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('email', models.EmailField(max_length=254)),
                ('english', models.BooleanField(default=False)),
                ('land', models.CharField(choices=[('BE', 'Belgique'), ('Fr', 'France'), ('DE', 'Allemagne'), ('IT', 'Italie')], max_length=25)),
            ],
        ),
    ]
