# Generated by Django 4.0.6 on 2022-07-29 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2022)])),
                ('author', models.CharField(max_length=100)),
                ('english', models.BooleanField(default=False)),
                ('land_production', models.CharField(choices=[('BE', 'Belgique'), ('Fr', 'France'), ('DE', 'Allemagne'), ('IT', 'Italie')], max_length=25)),
                ('official_page', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelPerson',
        ),
    ]
